name: Eslint
on: push
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Linter
      - uses: hallee/eslint-action@1.0.3
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          eslint-rc: .eslintrc.js